spring:
 profiles: prof2
 application:
    name: eureka-server
eureka:
 instance:
   preferIpAddress: true
   hostname: peer2
   metadataMap:
     zone: zone2
 client:
   registerWithEureka: true
   fetchRegistry: true 
   serviceUrl:
     defaultZone: http://localhost:8761/eureka/
     preferSameZoneEureka: true
server: 
 port: ${PORT:8762}